import { createClient } from 'npm:@supabase/supabase-js@2'
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'}
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json; charset=utf-8'}})
const key=(s:string)=>{try{const x=JSON.parse(s);return x.default||Object.values(x)[0]||''}catch{return ''}}
const compatible=(m:string,n:string)=>{const mime=String(m||'').toLowerCase(),e=String(n||'').toLowerCase().split('.').pop()||'';return ['text/plain','text/csv','application/json','text/markdown'].includes(mime)||['txt','csv','json','md','log'].includes(e)}
const clean=(s:string)=>String(s||'').replace(/\r\n?/g,'\n').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,' ').trim();const split=(s:string,n=1800)=>{const x=clean(s),out:string[]=[];for(let i=0;i<x.length;i+=n){const p=x.slice(i,i+n).trim();if(p)out.push(p)}return out}
Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'method_not_allowed'},405);const auth=req.headers.get('Authorization');if(!auth?.startsWith('Bearer '))return json({error:'missing_authorization'},401)
 const url=Deno.env.get('SUPABASE_URL'),pr=Deno.env.get('SUPABASE_PUBLISHABLE_KEYS'),sr=Deno.env.get('SUPABASE_SECRET_KEYS');if(!url||!pr||!sr)return json({error:'runtime_not_configured'},500);const publishable=key(pr),secret=key(sr);if(!publishable||!secret)return json({error:'keys_unavailable'},500)
 const userClient=createClient(url,publishable,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});const {data:{user},error:ue}=await userClient.auth.getUser();if(ue||!user)return json({error:'invalid_session'},401);const {data:profile,error:pe}=await userClient.from('profiles').select('industry_id').eq('id',user.id).single();if(pe||!profile?.industry_id)return json({error:'profile_not_found'},403)
 const admin=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});const {data:docs,error:de}=await admin.from('documents').select('id,filename,mime_type,storage_path').eq('industry_id',profile.industry_id);if(de)return json({error:'documents_query_failed',detail:de.message},500);const candidates=(docs||[]).filter(d=>d.storage_path&&compatible(d.mime_type,d.filename)),ids=candidates.map(d=>d.id);const {data:existing,error:ce}=ids.length?await admin.from('document_chunks').select('document_id').in('document_id',ids):{data:[],error:null};if(ce)return json({error:'chunks_query_failed',detail:ce.message},500)
 const indexed=new Set((existing||[]).map(c=>c.document_id)),pending=candidates.filter(d=>!indexed.has(d.id)),results=[];let indexedCount=0
 for(const doc of pending){try{const {data:file,error:fe}=await admin.storage.from('pulse-documents').download(doc.storage_path);if(fe||!file)throw new Error('STORAGE_DOWNLOAD');let text=await file.text();const ext=String(doc.filename||'').toLowerCase().split('.').pop()||'';if(ext==='json'||String(doc.mime_type||'').toLowerCase()==='application/json'){try{text=JSON.stringify(JSON.parse(text),null,2)}catch{}}const parts=split(text);if(!parts.length)throw new Error('EMPTY_TEXT');const rows=parts.map((content,chunk_index)=>({industry_id:profile.industry_id,document_id:doc.id,chunk_index,content,source_type:ext==='csv'?'csv':ext==='json'?'json':'text'}));const {error:up}=await admin.from('document_chunks').upsert(rows,{onConflict:'document_id,chunk_index',ignoreDuplicates:true});if(up)throw new Error('CHUNK_UPSERT');indexedCount++;results.push({document_id:doc.id,status:'indexed',chunks:parts.length})}catch(e){results.push({document_id:doc.id,status:'skipped',reason:String(e?.message||'INDEX_FAILED')})}}
 return json({industry_id:profile.industry_id,indexed:indexedCount,pending:pending.length,skipped:results.filter(r=>r.status==='skipped').length,results})
})