import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const origin = "https://paulorafaeldemourapaes.github.io";
const supabaseUrl = Deno.env.get("SUPABASE_URL") ?? "";
const keys = [Deno.env.get("SUPABASE_PUBLISHABLE_KEY") ?? "", Deno.env.get("SUPABASE_ANON_KEY") ?? ""].filter(Boolean);
const cors = {"Access-Control-Allow-Origin":origin,"Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"content-type, apikey, authorization","Cache-Control":"no-store","Content-Type":"application/json"};
function json(body: unknown,status=200){return new Response(JSON.stringify(body),{status,headers:cors})}
async function upstream(path:string,init:RequestInit){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);try{let last:Response|null=null;for(const apiKey of keys){const r=await fetch(supabaseUrl+path,{...init,signal:controller.signal,headers:{apikey:apiKey,...(init.headers??{})}});last=r;if(r.status!==401&&r.status!==403)return r}return last!}finally{clearTimeout(timer)}}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors});if(req.method!=="POST")return json({error:"method_not_allowed"},405);if(req.headers.get("origin")!==origin)return json({error:"origin_not_allowed"},403);let input:any;try{input=await req.json()}catch{return json({error:"invalid_json"},400)}try{
if(input?.action==="login"){const email=String(input.email??"").trim(),password=String(input.password??"");if(!email||!password)return json({error:"invalid_request"},400);const r=await upstream("/auth/v1/token?grant_type=password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});return new Response(await r.text(),{status:r.status,headers:cors})}
if(input?.action==="refresh"){const refreshToken=String(input.refresh_token??"");if(!refreshToken)return json({error:"invalid_request"},400);const r=await upstream("/auth/v1/token?grant_type=refresh_token",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({refresh_token:refreshToken})});return new Response(await r.text(),{status:r.status,headers:cors})}
if(input?.action==="recover"){const email=String(input.email??"").trim(),redirectTo=String(input.redirect_to??"");if(!email||redirectTo!==origin+"/shopplosion-pulse/auth.html")return json({error:"invalid_request"},400);const r=await upstream("/auth/v1/recover?redirect_to="+encodeURIComponent(redirectTo),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})});return new Response(await r.text(),{status:r.status,headers:cors})}
if(input?.action==="industry_context"){const accessToken=String(input.access_token??"");if(!accessToken)return json({error:"invalid_request"},400);const r=await upstream("/rest/v1/rpc/auth_industry_context",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+accessToken},body:"{}"});return new Response(await r.text(),{status:r.status,headers:cors})}
if(input?.action==="update_password"){const accessToken=String(input.access_token??""),password=String(input.password??"");if(!accessToken||!password||password.length<8)return json({error:"invalid_request"},400);const r=await upstream("/auth/v1/user",{method:"PUT",headers:{"Content-Type":"application/json",Authorization:"Bearer "+accessToken},body:JSON.stringify({password})});return new Response(await r.text(),{status:r.status,headers:cors})}
return json({error:"unknown_action"},400)}catch{return json({error:"upstream_unreachable"},504)}});