import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,x-pulse-cron","Access-Control-Allow-Methods":"POST,OPTIONS"};const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function sha(s:string){const h=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return Array.from(new Uint8Array(h)).map(x=>x.toString(16).padStart(2,"0")).join("");}
const clean=(s:string)=>String(s||"").replace(/<!\[CDATA\[|\]\]>/g,"").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g," ").trim();
const tag=(xml:string,name:string)=>{const m=xml.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,`i`));return m?clean(m[1]):"";};
const blocks=(xml:string,name:string)=>Array.from(xml.matchAll(new RegExp(`<${name}\\b[^>]*>([\\s\\S]*?)<\\/${name}\\s*>`,`gi`))).map(m=>m[1]);
function parseRss(xml:string){return blocks(xml,"item").slice(0,50).map((b,i)=>{const title=tag(b,"title")||`item-${i+1}`;const link=tag(b,"link")||tag(b,"guid");const guid=tag(b,"guid")||link||`${i}-${title}`;const desc=tag(b,"description")||tag(b,"content:encoded");const pub=tag(b,"pubDate")||tag(b,"published")||tag(b,"updated");return {external_id:guid,title,url:link,published_at:pub,content:clean(`${title}. ${desc}`)};}).filter(x=>x.content.length>=30);}
function parseAtom(xml:string){return blocks(xml,"entry").slice(0,50).map((b,i)=>{const title=tag(b,"title")||`entry-${i+1}`;const link=(b.match(/<link[^>]+href=["']([^"']+)["']/i)||[])[1]||"";const id=tag(b,"id")||link||`${i}-${title}`;const content=tag(b,"content")||tag(b,"summary");const pub=tag(b,"published")||tag(b,"updated");return {external_id:id,title,url:link,published_at:pub,content:clean(`${title}. ${content}`)};}).filter(x=>x.content.length>=30);}
async function fetchWithTimeout(url:string){const c=new AbortController();const t=setTimeout(()=>c.abort(),15000);try{return await fetch(url,{signal:c.signal,redirect:'follow',headers:{"User-Agent":"Shopplosion-Pulse/1.0","Accept":"application/rss+xml,application/atom+xml,application/json,text/html;q=0.9,*/*;q=0.8"}})}finally{clearTimeout(t)}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'method_not_allowed'},405);const url=Deno.env.get('SUPABASE_URL'),sr=Deno.env.get('SUPABASE_SECRET_KEYS');if(!url||!sr)return json({error:'runtime_not_configured'},500);const parsed=JSON.parse(sr),key=parsed.default||Object.values(parsed)[0];const admin=createClient(url,key as string,{auth:{persistSession:false,autoRefreshToken:false}});const {data:expected}=await admin.rpc('pulse_intelligence_worker_token');if(!expected||req.headers.get('x-pulse-cron')!==expected)return json({error:'internal_auth_failed'},403);const {data:sources,error:se}=await admin.from('intelligence_sources').select('id,industry_id,name,source_type,url,poll_interval_minutes,last_fetched_at').eq('active',true);if(se)return json({error:'sources_query_failed'},500);let fetched=0,seen=0,changed=0,failed=0;for(const s of sources||[]){if(s.last_fetched_at&&Date.now()-new Date(s.last_fetched_at).getTime()<Number(s.poll_interval_minutes||180)*60000)continue;fetched++;const {data:run}=await admin.from('intelligence_source_fetch_runs').insert({source_id:s.id,industry_id:s.industry_id,status:'running'}).select('id').single();let itemsSeen=0,itemsChanged=0;try{let response:Response|null=null;for(let a=0;a<3;a++){try{response=await fetchWithTimeout(s.url);if(response.ok)break;}catch{}if(a<2)await sleep(500*(a+1));}if(!response?.ok)throw new Error(`http_${response?.status||0}`);const body=await response.text();let items:any[]=[];if(s.source_type==='rss')items=/<feed\b/i.test(body)?parseAtom(body):parseRss(body);else if(s.source_type==='json'){const j=JSON.parse(body);const arr=Array.isArray(j)?j:(Array.isArray(j.items)?j.items:(Array.isArray(j.data)?j.data:[]));items=arr.slice(0,50).map((x:any,i:number)=>({external_id:String(x.id||x.guid||x.url||i),title:String(x.title||x.name||`item-${i+1}`),url:String(x.url||x.link||''),published_at:String(x.published_at||x.published||x.date||x.updated||''),content:clean(`${x.title||x.name||''}. ${x.description||x.summary||x.content||''}`)})).filter(x=>x.content.length>=30);}else{const title=tag(body,'title')||s.name;items=[{external_id:s.url,title,url:s.url,published_at:'',content:clean(`${title}. ${body}`).slice(0,12000)}];}
for(const item of items){itemsSeen++;const fp=await sha(`${item.title}|${item.url}|${item.content}`);const {data:old}=await admin.from('intelligence_source_items').select('id,content_fingerprint').eq('source_id',s.id).eq('external_id',String(item.external_id)).maybeSingle();const d=item.published_at?new Date(item.published_at):null;const publishedAt=d&&!Number.isNaN(d.getTime())?d.toISOString():null;const {error}=await admin.from('intelligence_source_items').upsert({source_id:s.id,industry_id:s.industry_id,external_id:String(item.external_id).slice(0,1000),title:String(item.title).slice(0,500),url:item.url?String(item.url).slice(0,2000):null,published_at:publishedAt,content:String(item.content).slice(0,12000),content_fingerprint:fp,fetched_at:new Date().toISOString(),status:'active'},{onConflict:'source_id,external_id'});if(!error&&(!old||old.content_fingerprint!==fp))itemsChanged++;}
const now=new Date().toISOString();await admin.from('intelligence_sources').update({last_fetched_at:now,last_success_at:now,last_error:null,updated_at:now}).eq('id',s.id);await admin.from('intelligence_source_fetch_runs').update({finished_at:now,status:'completed',items_seen:itemsSeen,items_changed:itemsChanged}).eq('id',run?.id);seen+=itemsSeen;changed+=itemsChanged;}catch(e){failed++;const now=new Date().toISOString();await admin.from('intelligence_sources').update({last_fetched_at:now,last_error:String(e).slice(0,500),updated_at:now}).eq('id',s.id);await admin.from('intelligence_source_fetch_runs').update({finished_at:now,status:'failed',items_seen:itemsSeen,items_changed:itemsChanged,error:String(e).slice(0,500)}).eq('id',run?.id);}}return json({status:'completed',sources_fetched:fetched,items_seen:seen,items_changed:changed,sources_failed:failed});});
