import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,x-pulse-cron","Access-Control-Allow-Methods":"POST,OPTIONS"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});
async function sha(s:string){const h=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return Array.from(new Uint8Array(h)).map(x=>x.toString(16).padStart(2,"0")).join("")}
Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'method_not_allowed'},405);
 const url=Deno.env.get('SUPABASE_URL'),sr=Deno.env.get('SUPABASE_SECRET_KEYS');if(!url||!sr)return json({error:'runtime_not_configured'},500);
 let key:string;try{const parsed=JSON.parse(sr);key=parsed.default||Object.values(parsed)[0] as string}catch{return json({error:'secret_parse_failed'},500)}
 const admin=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const {data:expected}=await admin.rpc('pulse_intelligence_worker_token');if(!expected||req.headers.get('x-pulse-cron')!==expected)return json({error:'internal_auth_failed'},403);
 const cutoff=new Date(Date.now()-30*86400000).toISOString();const {data:items,error}=await admin.from('intelligence_source_items').select('id,source_id,industry_id,title,url,published_at,content,fetched_at').eq('status','active').gte('fetched_at',cutoff).order('published_at',{ascending:false,nullsFirst:false}).limit(200);if(error)return json({error:'items_query_failed',detail:error.message},500);
 let checked=0,created=0,events=0;const errors:string[]=[];for(const item of items||[]){checked++;const {data:c,error:ce}=await admin.rpc('pulse_external_intelligence_fallback_candidate',{p_item_id:item.id});if(ce){errors.push(`candidate:${item.id}:${ce.message}`);continue}if(!c?.title||!Array.isArray(c.evidence)||!c.evidence.length)continue;const quote=String(c.evidence[0]?.quote||'');if(!quote||!String(item.content||'').includes(quote))continue;const signalType=['trend','change','risk','opportunity','competitor','pricing','channel','demand','other'].includes(c.signal_type)?c.signal_type:'change';const signalKey=await sha(`${item.industry_id}|${signalType}|${String(c.title).trim().toLowerCase()}`);const evidence=[{source_item_id:item.id,source_id:item.source_id,source_url:item.url,source_title:item.title,published_at:item.published_at,quote:quote.slice(0,700)}];const fingerprint=await sha(`${signalKey}|${String(c.summary||'').trim().toLowerCase()}|${JSON.stringify(evidence)}`);const {data:existing}=await admin.from('intelligence_signals').select('id,confidence,fingerprint').eq('industry_id',item.industry_id).eq('signal_key',signalKey).maybeSingle();const payload={industry_id:item.industry_id,signal_type:signalType,title:String(c.title).slice(0,180),summary:String(c.summary).slice(0,1500),confidence:Number(c.confidence)||0.72,evidence,source_document_ids:[],status:'active',observed_at:new Date().toISOString(),updated_at:new Date().toISOString(),fingerprint,signal_key:signalKey};let signalId=existing?.id as string|undefined;if(!signalId){const {data:ins,error:ie}=await admin.from('intelligence_signals').insert(payload).select('id').single();if(ie||!ins){errors.push(`signal:${item.id}:${ie?.message||'insert_failed'}`);continue}signalId=ins.id;created++}else{const {error:ue}=await admin.from('intelligence_signals').update(payload).eq('id',signalId);if(ue){errors.push(`signal_update:${item.id}:${ue.message}`);continue}}
 const prior=existing?.confidence==null?null:Number(existing.confidence);if(prior===null||existing?.fingerprint!==fingerprint||Math.abs(Number(c.confidence)-prior)>=.05){const {error:ee}=await admin.from('intelligence_signal_events').insert({signal_id:signalId,industry_id:item.industry_id,fingerprint,direction:prior===null?'new':Number(c.confidence)>=prior?'up':'down',confidence:Number(c.confidence)||0.72,change_score:Number(c.change_score)||0.35,evidence});if(!ee)events++;else errors.push(`event:${item.id}:${ee.message}`)}}
 return json({status:'completed',items_checked:checked,signals_created:created,events_created:events,errors:errors.slice(0,10)});
});