import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:cors});
Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'METHOD_NOT_ALLOWED'},405);try{
  const auth=req.headers.get('Authorization')||'';if(!auth.startsWith('Bearer '))return json({error:'UNAUTHORIZED'},401);
  const supabase=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});const {data:{user},error:userError}=await supabase.auth.getUser();if(userError||!user)return json({error:'UNAUTHORIZED'},401);
  const {data:profile,error:profileError}=await supabase.from('profiles').select('industry_id').eq('id',user.id).single();if(profileError||!profile)return json({error:'PROFILE_NOT_FOUND'},403);const body=await req.json().catch(()=>({}));const documentId=typeof body.document_id==='string'?body.document_id:null;if(!documentId)return json({error:'DOCUMENT_ID_REQUIRED'},400);
  const {data:doc,error:docError}=await supabase.from('documents').select('id,industry_id,filename,mime_type,storage_path').eq('id',documentId).eq('industry_id',profile.industry_id).single();if(docError||!doc)return json({error:'DOCUMENT_NOT_FOUND'},404);const {count,error:countError}=await supabase.from('document_chunks').select('id',{count:'exact',head:true}).eq('document_id',documentId).eq('industry_id',profile.industry_id);if(countError)return json({error:'CHUNK_COUNT_FAILED'},500);if((count||0)>0)return json({ok:true,status:'already_indexed',chunks:count});
  const {data:file,error:downloadError}=await supabase.storage.from('pulse-documents').download(doc.storage_path);if(downloadError||!file)return json({error:'STORAGE_DOWNLOAD_FAILED',detail:downloadError?.message||'empty'},502);const mime=String(doc.mime_type||'').toLowerCase(),ext=String(doc.filename||'').toLowerCase().split('.').pop()||'';const textExts=['txt','csv','json','md','log'];if(!(mime==='text/plain'||mime==='text/csv'||mime==='application/json'||mime==='text/markdown'||mime==='application/pdf'||textExts.includes(ext)))return json({error:'UNSUPPORTED_TYPE'},415);if(mime==='application/pdf'||ext==='pdf')return json({error:'PDF_BROWSER_INDEX_REQUIRED',status:'pending_pdf',message:'PDF extraction remains browser-side to avoid silently failing on scanned PDFs.'},422);
  const raw=await file.text();const text=ext==='json'?(()=>{try{return JSON.stringify(JSON.parse(raw),null,2)}catch{return raw}})():raw;const normalized=text.replace(/\r\n?/g,'\n').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,' ').trim();if(!normalized)return json({error:'TEXT_EMPTY'},422);const chunks:string[]=[];for(let i=0;i<normalized.length;i+=1800)chunks.push(normalized.slice(i,i+1800).trim());const sourceType=ext==='csv'?'csv':ext==='json'?'json':'text';const rows=chunks.filter(Boolean).map((content,chunk_index)=>({industry_id:profile.industry_id,document_id:documentId,chunk_index,content,source_type:sourceType}));const {error:insertError}=await supabase.from('document_chunks').upsert(rows,{onConflict:'document_id,chunk_index',ignoreDuplicates:true});if(insertError)return json({error:'CHUNK_INSERT_FAILED',detail:insertError.message},500);const {count:finalCount}=await supabase.from('document_chunks').select('id',{count:'exact',head:true}).eq('document_id',documentId).eq('industry_id',profile.industry_id);return json({ok:true,status:'indexed',chunks:finalCount||rows.length});
 }catch(error){return json({error:'INTERNAL_ERROR',detail:String(error?.message||error)},500)}});
